# Render Configuration
services:
  - type: web
    name: hackathon-platform
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hackathon-db
          property: connectionString
    
databases:
  - name: hackathon-db
    databaseName: hackathon_production
    user: hackathon_user
